
GOOGLE_TOKEN = """
{
  "token": "ya29.a0AW4XtxhZA_xtrWDptGpP0CSQuIsxIG-2cJlSKQO2dkWSF5csz6FkVWQVXvet_05aW8JZKMT7G9cbOXNMBl9Pxoe5GCaqsynFIdiLgkaDhK6PO8mcuVcv_s_1QfZpyGTMx-4M9ca7nwalhwJxfxPKVba5UXSMi8QrjJafeYceuf4aCgYKAdkSAQ4SFQHGX2MiA-iAp4Xvoq6J2SEJfZUt_g0178",
  "refresh_token": "1//0hoA5FUtBkP2dCgYIARAAGBESNwF-L9IrQnqXtSlFKsEvf8oMZIYrFr4RlXj00-qGhSW-V1mAocDrtbaA3no-49_AWPQ93HaM0VE",
  "token_uri": "https://oauth2.googleapis.com/token",
  "client_id": "644375401199-08mmuj931kkn4jgck6nslcgcvttd5k6r.apps.googleusercontent.com",
  "client_secret": "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",
  "scopes": ["https://www.googleapis.com/auth/spreadsheets"],
  "universe_domain": "googleapis.com",
  "account": "",
  "expiry": "2025-05-27T16:22:23.757167Z"
  
}
"""
# .streamlit/secrets.toml (no deploy)
PRINT_SERVER_URL = "https://epson6.podeconfiar.app"
PRINT_TOKEN      = "12345678"
